Repository CodigoVital/Vital-IA, pull requests merged in 2025-09, with the labels that each got.

#15 UI: Diseñar componente ChatMessage y vista ChatWindowView
  package-lock.json
  package.json
  src/components/app-sidebar.tsx
  src/components/custom/CustomHeader.tsx
  src/components/nav-main.tsx
  src/components/nav-user.tsx
  src/components/ui/button.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/sidebar.tsx
  src/layouts/dashboard-layout.tsx
  src/sections/chat/components/chat-header.tsx
  src/sections/chat/components/chat-message.tsx
  src/sections/chat/view/chat-main-view.tsx
  src/sections/chat/view/chat-suggest-view.tsx
  src/sections/chat/view/chat-window-view.tsx
  src/sections/chat/view/data/message.mock.ts
  src/sections/chat/view/data/suggest.mock.ts
Labels: documentation, enhancement

#20 Development
  src/App.tsx
  src/components/app-sidebar.tsx
  src/index.css
  src/layouts/dashboard-layout.tsx
  src/main.tsx
  src/sections/chat/components/chat-input.tsx
  src/sections/chat/components/chat-message.tsx
  src/sections/chat/view/chat-suggest-view.tsx
  src/sections/chat/view/chat-window-view.tsx
  src/sections/chat/view/data/suggest.mock.ts
Labels: style

#21 feat: Configurar Redux con Redux Toolkit
  package-lock.json
  package.json
  src/layouts/dashboard-layout.tsx
  src/main.tsx
  src/store/store.ts
Labels: enhancement

#24 style: Agregar mejoras en animaciones y iconos
  src/components/app-sidebar.tsx
  src/components/config/sidebar-data.ts
  src/components/lucide-icon-name.tsx
  src/components/nav-main.tsx
  src/components/nav-user.tsx
  src/components/ui/sidebar.tsx
  src/sections/chat/components/chat-input.tsx
  src/sections/chat/view/chat-suggest-view.tsx
Labels: style

#25 Development
  README.md
  src/components/app-sidebar.tsx
  src/components/config/sidebar-data.ts
  src/components/lucide-icon-name.tsx
  src/components/nav-main.tsx
  src/components/nav-user.tsx
  src/components/ui/sidebar.tsx
  src/sections/chat/components/chat-input.tsx
  src/sections/chat/view/chat-suggest-view.tsx
Labels: style

#27 feature: Responsividad del DashboardLayout
  src/components/custom/CustomHeader.tsx
  src/components/custom/custom-header.tsx
  src/components/nav-main.tsx
  src/components/ui/sidebar.tsx
  src/layouts/dashboard-layout.tsx
  src/sections/chat/components/chat-message.tsx
  src/sections/chat/view/chat-main-view.tsx
Labels: enhancement, style

#29 fix: adjust layout styles for mobile view in DashboardLayout component
  src/layouts/dashboard-layout.tsx
Labels: bug, style

#18 13 UI crear página diagnostico siguiendo la estructura del chat
  .hintrc
  index.html
  package-lock.json
  package.json
  src/components/custom/custom-popup.tsx
  src/components/ui/popover.tsx
  src/routes/AppRouter.tsx
  src/sections/diagnostico/hooks/use-diagnostico.ts
  src/sections/diagnostico/view/diagnostico-main-view.tsx
  src/sections/diagnostico/view/resultado-view.tsx
Labels: enhancement

#35 refactor: mejorar modularidad, estilos y responsividad de la página de diagnóstico con shadcn/ui
  public/assets/svg/shield-heart.svg
  src/Page/diagnosis/diagnosisPage.tsx
  src/components/app-sidebar.tsx
  src/components/custom/custom-alert.tsx
  src/components/custom/custom-dialog.tsx
  src/components/custom/custom-header.tsx
  src/components/custom/custom-popup.tsx
  src/components/lucide-icon-name.tsx
  src/components/nav-main.tsx
  src/components/ui/alert.tsx
  src/components/ui/card.tsx
  src/components/ui/dialog.tsx
  src/index.css
  src/routes/AppRouter.tsx
  src/sections/chat/components/chat-suggest.tsx
  src/sections/chat/components/chat-window.tsx
  src/sections/chat/view/chat-main-view.tsx
  src/sections/diagnosis/components/info-card.tsx
  src/sections/diagnosis/components/symptom-chips-list.tsx
  src/sections/diagnosis/components/symptom-common-list.tsx
  src/sections/diagnosis/components/symptom-input.tsx
  src/sections/diagnosis/components/symptom-instructions.tsx
  src/sections/diagnosis/components/symptom-selected-list.tsx
  src/sections/diagnosis/data/recommendations.mock.ts
  src/sections/diagnosis/data/symptom.mock.ts
  src/sections/diagnosis/hooks/use-diagnostico.ts
  src/sections/diagnosis/view/diagnosis-main-view.tsx
  src/sections/diagnosis/view/result-view.tsx
  src/sections/diagnostico/view/diagnostico-main-view.tsx
  src/sections/diagnostico/view/resultado-view.tsx
Labels: enhancement, style, refactor

#36 Development
  .hintrc
  index.html
  package-lock.json
  package.json
  public/assets/svg/shield-heart.svg
  src/Page/diagnosis/diagnosisPage.tsx
  src/components/app-sidebar.tsx
  src/components/custom/custom-alert.tsx
  src/components/custom/custom-dialog.tsx
  src/components/custom/custom-header.tsx
  src/components/lucide-icon-name.tsx
  src/components/nav-main.tsx
  src/components/ui/alert.tsx
  src/components/ui/card.tsx
  src/components/ui/dialog.tsx
  src/components/ui/popover.tsx
  src/index.css
  src/routes/AppRouter.tsx
  src/sections/chat/components/chat-suggest.tsx
  src/sections/chat/components/chat-window.tsx
  src/sections/chat/view/chat-main-view.tsx
  src/sections/diagnosis/components/info-card.tsx
  src/sections/diagnosis/components/symptom-chips-list.tsx
  src/sections/diagnosis/components/symptom-common-list.tsx
  src/sections/diagnosis/components/symptom-input.tsx
  src/sections/diagnosis/components/symptom-instructions.tsx
  src/sections/diagnosis/components/symptom-selected-list.tsx
  src/sections/diagnosis/data/recommendations.mock.ts
  src/sections/diagnosis/data/symptom.mock.ts
  src/sections/diagnosis/hooks/use-diagnostico.ts
  src/sections/diagnosis/view/diagnosis-main-view.tsx
  src/sections/diagnosis/view/result-view.tsx
Labels: enhancement, style

#41 Development
  package-lock.json
  package.json
  public/assets/img/alimentacion.jpg
  public/assets/img/estres.webp
  public/assets/img/hidratacion.jpg
  public/assets/img/prevencion.webp
  public/assets/img/sueno.jpg
  public/assets/img/vacunacion.jpg
  src/Page/health-info/health-info-page.tsx
  src/components/config/sidebar-data.ts
  src/components/ui/sidebar.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/index.css
  src/routes/AppRouter.tsx
  src/sections/health-info/components/health-article-card.tsx
  src/sections/health-info/components/health-article-grid.tsx
  src/sections/health-info/components/health-category-filter.tsx
  src/sections/health-info/config/categories.config.ts
  src/sections/health-info/data/health-info.mock.ts
  src/sections/health-info/hooks/use-health-info.ts
  src/sections/health-info/types/category.ts
  src/sections/health-info/types/info.ts
  src/sections/health-info/views/health-info-main-view.tsx
Labels: enhancement, style

#42 fix: update README.md for clarity and improved structure
  README.md
Labels: documentation

#50 fix: Add background color to Logo component for improved visibility
  src/components/app-sidebar.tsx
  src/components/logo.tsx
Labels: bug

#51 fix: Remove background color from Logo component for consistency
  src/components/app-sidebar.tsx
Labels: bug, style
